examples/langchainExample.ts, package-lock.json, package.json, src/index.ts, src/langchain/retriever.ts, tests/langchain.test.ts
Add langchain retriever and rag example
=> Add langchain retriever and rag example

package.json, packages/langchain/package.json, src/client.ts, src/types.ts, tests/client.test.ts
- Get content and getcontentbyid will add content_url property
- Add download content test and updates to getcontent tests
=> Add downloadContent method and content_url property for IContentMetadata

package.json, src/client.ts, src/index.ts, src/types.ts
add getSchemas method to client
=> Add schemas to client

package.json, src/types.ts
add size to content metadata type
=> Add size to metadata types

package.json, src/client.ts
support remote files in client
=> Set content url to remote storage url if http

package-lock.json, package.json, src/client.ts
update policy id in createclient
=> Update createclient add extraction policy id

.gitignore, package-lock.json, package.json, src/client.ts, src/types.ts, tests/client.test.ts
support mtls in client
static methods and create client now have optional mtlsConfig:
certPath: string;
keyPath: string;
caPath?: string; //optional
=> Add support for mtls

package.json, src/client.ts
=> Add ingest remote file method

package-lock.json, package.json, packages/langchain/package.json, src/client.ts
added generateUniqueHexId generateHashFromString
=> add hash functions

package.json, src/client.ts
=> Fix get content metadata method

.github/workflows/publish.yaml, .npmignore, package.json, packages/langchain/.npmignore, packages/langchain/README.md, packages/langchain/package-lock.json, packages/langchain/package.json, packages/langchain/tsconfig.json
=> Update langchain retriever to use dist

package.json, src/client.ts
add optional include_content on search index (defaults to true)
=> Add include_content param on search index

package.json, src/types.ts, tests/client.test.ts
update types for icontentmetadata
update tests
=> Update types for content metadata responses

package-lock.json, package.json, src/client.ts, tests/client.test.ts
=> Update crypto and https imports for isomorphic support

package.json, src/index.ts, src/types.ts
=> Update types for task outcome

README.md, examples/.gitignore, examples/README.md, examples/extractContent.ts, examples/langchainRag.ts, examples/openaiRag.ts, examples/package-lock.json, examples/package.json, examples/tsconfig.json, package.json, packages/langchain/package.json
add more comprehensive readme and update examples for langchain, openai and extract content
=> Update TypeScript examples and READMEs 

package.json, packages/langchain/package.json, src/client.ts
support content pagination and tasks with limit and startId
=> Support pagination for content and tasks

package.json, src/client.ts, tests/client.test.ts
fix upload with labels by changing order of multipart form upload
tested on browser and non browser
=> Fix upload file labels

package.json, src/client.ts, tests/client.test.ts
support totals for getExtractedContent and getTasks
=> Support totals for getExtractedContent  getTasks

package.json, src/client.ts
add outcome filter to gettasks to count by status
=> Add outcome filter to getTasks

package-lock.json, package.json, src/client.ts
Added a filter to list extracted content by ingested content id
=> Added a filter to list extracted content by ingested content id
